[project]
name = "cc-web-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agno>=2.2.10",
    "openai>=2.7.1",
    "yfinance>=0.2.66",
]
